version: "3"
services:

  postgres:
    image: postgres:11.3
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  app:
    build: ./
    restart: on-failure
    ports:
      - 8081:5000
    environment:
      DB_NAME: "postgres"
      DB_USER: "postgres"
      DB_HOST: postgres
      DB_PASSWORD: "postgres"
    depends_on:
      - postgres
